version: '3.9' # kommentit, tässä docker versio
services:
  php-env:
    build:
      context: .  
      dockerfile: Dockerfile 
    volumes:
      - ./src:/var/www/html
    ports:
      - 9000:80 # tällä osoitteella otetaan yhteys selaimella
    depends_on:
      - mysql_db
  mysql_db:
    image: mysql:8.3 # latest ei toimi, valitaan 8.3 versio
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 9001:80 # tällä osoitteella otetaan yhteys selaimella
    environment:
      PMA_ARBITRARY: 1  
    depends_on:
      - mysql_db